### PR TITLE
Feature/integrate lp rewards endpoint

### PR DESCRIPTION
**Pull request by alanrsoares**
* Total LPPD rewards header added to Pool page
* Per pool LPPD rewards added to pool details
* Rewards distributed to the pool are hidden when rewardsPeriod.distributed is false
* add `stake` cta for each LPPD reward line

image

### CODE REVIEW

**Review by oieduardorabelo — APPROVED** [review]
I don't have the full context of this project + biz-reqs. I couldn't find anything out of the ordinary from a coding perspective. LGTM.

**Comment by ghuznee** [comment]
@pgoos this is ready for testing. Is there anything you need to get the testing underway?

**Comment by alanrsoares** [comment]
@pgoos @daechoi I made a change to only display the pool's redistribution if there isn't an entry for the given pool in the LPPD response.

**Comment by pgoos** [comment]
TestNet testing:

1. for the pools I have shares in, I cannot expand them to see the details

2. not sure, if this is deliberate, but there are pools like ATOM/Rowan, USDC/Rowan where I don’t have any liquidity in but they do display my rewards and LP distribution values. 

3. My balances keep loading endlessly (“Loading Balances”) but in Keplr I see a certain number of Rowan (very slowly growing but growing)

4. I cannot expand many of the pools details, only few are expandable (eth/rowan, usdc/rowan, atom/rowan to name a few)

**Comment by pgoos** [comment]
Ad. 3 could that be a causing error for balances not loading?

**Comment by alanrsoares** [comment]
@pgoos updated to match the new response from DataServices

**Comment by pgoos** [comment]
@ghuznee 
All issues but #3 are fixed now.
#3 seems to be a sifnode related which is tracked by https://app.zenhub.com/workspaces/current-sprint---engineering-615a2e9fe2abd5001befc7f9/issues/sifchain/sifnode/3088

**Comment by ghuznee** [comment]
@pgoos- great job. is there any merging that needs to happen?

**Comment by alanrsoares** [comment]
@pgoos all changes are pushed to the branch now

**Pull request merged**
